/**
 * Represents the metadata associated to a Dart Frog application.
 */
export class DartFrogApplication {
  // TODO(alestiago): Include constructor that finds available ports.
  constructor(port: number, vmServicePort: number, projectPath: string) {
    this.port = port;
    this.vmServicePort = vmServicePort;
    this.projectPath = projectPath;
  }

  /**
   * The port on which the application is listening.
   */
  public readonly port: number;

  /**
   * The port on which the VM service is listening.
   */
  public readonly vmServicePort: number;

  /**
   * The root path to the application's project directory.
   */
  public readonly projectPath: string;

  private _id: string | undefined;

  /**
   * The application's unique identifier.
   *
   * The application's unique identifier is generated by the Dart Frog Daemon
   * upon starting the application.
   *
   * It is undefined until the application has been started by the Dart Frog
   * Daemon, and in turn, has been assigned such identifier.
   */
  public get identifier(): string | undefined {
    return this._id;
  }

  /**
   * Sets the application's unique identifier.
   *
   * This method should only be called once, when the application is started and
   * has been assigned an identifier by the Dart Frog Daemon.
   *
   * If the application already has an identifier, this method will do nothing.
   */
  public set identifier(value: string) {
    if (this._id) {
      return;
    }

    this._id = value;
  }

  private _vmServiceUri: string | undefined;

  /**
   * The URI of the VM service.
   *
   * This is used to attach to the debug session.
   *
   * It is undefined until the application has been started by the Dart Frog
   * Daemon, and in turn, has been assigned such URI.
   */
  public get vmServiceUri(): string | undefined {
    return this._vmServiceUri;
  }

  /**
   * Sets the URI of the VM service.
   *
   * This method should only be called once, when the application is started and
   * has been assigned a VM service URI by the Dart Frog Daemon.
   *
   * If the application already has a VM service URI, this method will do
   * nothing.
   */
  public set vmServiceUri(value: string) {
    if (this._vmServiceUri) {
      return;
    }

    this._vmServiceUri = value;
  }
}
